#!/bin/bash

#longest word in a file

while [[ -n $1 ]]; do 
    if [[ -r $1 ]]; then
        max_word=
        max_len=0
        for i in $(strings $1); do 
            len=$( echo $i | wc -c)
            if (( len > max_len)); then
                max_word=$i
                max_len=$len
            fi
        done
        echo "$1: '$max_word' ($max_len) letters"
    fi
    shift
done
